title: ANUSA Clubs Resources
description: Resources for ANU Student Clubs and Societies
theme: just-the-docs
repository: anusaclubs/anusaclubs.github.io
baseurl: ""
url: https://anusaclubs.github.io
logo: "/images/general/anusa-cropped.png"
favicon_ico: "/images/general/anusa-favicon-24-01-150x150.png" 


aux_links:
  "Contribute":
    - "https://github.com/anusaclubs/anusaclubs.github.io"
  "Clubs Regulations":
    - "https://anusa.com.au/wp-content/uploads/2025/10/Regulations-8-October-2025.pdfpage=18"
